apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: ${NAMESPACE}-ing
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "${STATIC_IP_NAME}"
spec:
  tls:
  - secretName: ${SECRET}
  rules:
  - host: ${DOMAIN}
    http:
      paths:
      - path: /*
        backend:
          serviceName: ${APP_SERVICE}
          servicePort: 80