apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: letsencypt-ing
  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.global-static-ip-name: "${STATIC_IP_NAME}"
spec:
  tls:
  - secretName: ${SECRET}
  rules:
  - host: ${DOMAIN}
    http:
      paths:
      - path: /.well-known/*
        backend:
          serviceName: letsencrypt-svc
          servicePort: 80
      - path: /*
        backend:
          serviceName: ${APP_SERVICE}
          servicePort: 80